In [2]:
import numpy as np

## Populate arrays with specific numbers
Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [3]:
one_dim_array = np.array([1.1, 2.1, 3.5, 4.6, 5.9, 6.1, 8.2, 11.2])
print(one_dim_array)

[ 1.1  2.1  3.5  4.6  5.9  6.1  8.2 11.2]


You can also use `np.array` to create a two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [4]:
two_dim_array = np.array([[1, 2], [2, 3], [3, 4]])
print(two_dim_array)

[[1 2]
 [2 3]
 [3 4]]


## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


## Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100. 

In [6]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6,))
print(random_integers_between_50_and_100)

[64 77 64 60 61 58]


In [40]:
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1) 

[0.0934964  0.98319785 0.80162372 0.56781099 0.2228392  0.27109812]


## Mathematical Operations on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra.

In [41]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.0934964  2.98319785 2.80162372 2.56781099 2.2228392  2.27109812]


In [42]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[192 231 192 180 183 174]
